services:
  backend:
    build:
      context: ./backend_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./.streamlit:/.streamlit:ro
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

  frontend:
    build:
      context: ./frontend_service
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - PYTHONPATH=/app
      - BACKEND_URL=http://backend:8000
    volumes:
      - ./logs:/app/logs
      - ./.streamlit:/.streamlit:ro
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M

networks:
  default:
    driver: bridge
