AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to create an EC2 instance for IDS706 Final Project"

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-055e3d4f0bbeb5878 # Amazon Linux 2 AMI
      KeyName: my-key-pair # EC2 key pair
      SecurityGroupIds:
        - sg-028f15690c793835b # security group
      SubnetId: subnet-09c1963a3bdad91a1 # subnet ID
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y docker
          sudo service docker start
          sudo usermod -aG docker ec2-user
          docker run -d -p 8000:8000 -p 8501:8501 ${ECRImageUri}

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow HTTP, Streamlit, and SSH access"
      VpcId: vpc-001b691681d6a8c3d # VPC ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8501
          ToPort: 8501
          CidrIp: 0.0.0.0/0

Parameters:
  ECRImageUri:
    Type: String
    Description: "The URI of the Docker image in Amazon ECR"
