name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          pip install -r backend_service/requirements.txt
          pip install -r frontend_service/requirements.txt

      - name: Lint with ruff
        run: |
          ruff check .

      - name: Run tests with pytest
        run: |
          pytest

      - name: Format with black
        run: |
          black backend_service
          black frontend_service

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend_service
          push: false
          tags: backend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend_service
          push: false
          tags: frontend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
